{% set major_minor = "2.54" %}
{% set version = major_minor + ".1" %}
{% set sha256 = "7cc28c732b04d70ed34f0c923543129083cfb90580ea4a2b4be5b38802bf6a4a" %}
{% if linux %}
    {% set libext = ".so" %}
{% else %}
    {% set libext = ".dylib" %}
{% endif %}

package:
  name: glibmm
  version: {{ version }}

source:
  fn: glibmm-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/glibmm/{{ major_minor }}/glibmm-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - libsigcpp
    - glib 2.51.*
    - xz 5.2.*

test:
  commands:
    - test -f ${PREFIX}/lib/libgiomm-2.4{{ libext }}
    - test -f ${PREFIX}/lib/libglibmm-2.4{{ libext }}
    - test -f ${PREFIX}/lib/libglibmm_generate_extra_defs-2.4{{ libext }}

about:
  home: http://www.gtkmm.org
  license: LGPL v2.1
  license_file: COPYING
  summary: "This is glibmm, a C++ API for parts of glib that are useful for C++."

extra:
  recipe-maintainers:
    - scopatz
